import { User } from "discord.js";

export interface Character {
  user: User;
  name: string;
  level: number;
  ancestry?: string;
  heritage?: string;
  background?: string;
  class?: string;
  keyAbility?: "str" | "dex" | "con" | "int" | "wis" | "cha";
  alignment?: string;
  gender?: string;
  age?: string;
  deity?: string;
  size: number;
  languages: string[];
  attributes?: {
    ancestryHp?: number;
    classHp?: number;
    bonusHp?: number;
    bonusHpPerLevel?: number;
    speed?: number;
    speedBonus?: number;
  };
  abilities?: {
    str?: number;
    dex?: number;
    con?: number;
    int?: number;
    wis?: number;
    cha?: number;
  };
  proficiencies?: {
    classDC?: number;
    perception?: number;
    fortitude?: number;
    reflex?: number;
    will?: number;
    heavy?: number;
    medium?: number;
    light?: number;
    unarmored?: number;
    advanced?: number;
    martial?: number;
    simple?: number;
    unarmed?: number;
    castingArcane?: number;
    castingDivine?: number;
    castingOccult?: number;
    castingPrimal?: number;
    acrobatics?: number;
    arcana?: number;
    athletics?: number;
    crafting?: number;
    deception?: number;
    diplomacy?: number;
    intimidation?: number;
    medicine?: number;
    nature?: number;
    occultism?: number;
    performance?: number;
    religion?: number;
    society?: number;
    stealth?: number;
    survival?: number;
    thievery?: number;
  };
  lores?: { name: string; proficiency?: number }[];
  feats?: { name: string; source?: string; level?: number }[];
  specials?: string[];
  equipment?: { name: string; qty?: number }[];
  specificProficiencies?: {
    trained?: string[];
    expert?: string[];
    master?: string[];
    legendary?: string[];
  };
  weapons?: {
    name?: string;
    qty?: number;
    prof?: "unarmed" | "simple" | "martial" | "advanced";
    die?: string;
    pot?: number;
    str?: string;
    mat?: string;
    display?: string;
    runes?: string[];
  }[];
  money?: { pp?: number; gp?: number; sp?: number; cp?: number };
  armor?: {
    name?: string;
    qty?: number;
    prof?: "unarmored" | "light" | "medium" | "heavy";
    pot?: number;
    res?: string;
    mat?: string;
    display?: string;
    worn?: boolean;
    runes?: string[];
  }[];
  spellCasting?: {
    name: string;
    magicTradition?: "arcane" | "divine" | "occult" | "primal" | "focus";
    spellcastingType?: "prepared" | "spontaneous";
    ability?: "str" | "dex" | "con" | "int" | "wis" | "cha";
    proficiency?: number;
    focusPoints?: number;
    spells?: { spellLevel: number; list?: string[] }[];
    perDay?: number[];
  }[];
  formula?: string[];
  pets?: string[];
  ac?: {
    acProfBonus: number;
    acAbilityBonus: number;
    acItemBonus: number;
    acTotal: number;
  };
}
